
---
version: 0.2

phases:
  build:
    commands:
      # STEP1: FILTER GIT HISTORY TO ONLY FILES WE NEED TO WORK WITH INTO DIFFERENT SETS
      - python3.6 automation-changed-files-filter.py

      # STEP2: EXECUTE CF_NAG ON THE TEMPLATES CHANGE SET DIRECTORY - CF NAG WILL GO THROUGH THE DIRECTORY RECURSIVELY.
      - cfn_nag_scan --input-path templates-sync

      # TODO: STEP3: Sync all change sets into staging s3 bucket under a git hash. Invoke test lambdas passing the paths in S3 to each stack. Test lambda's defined in config, allowing additional pre-create tests to be written ad-hoc

      # STEP4: RUN SYNC: DOES STACK DELETES, TEMPLATE UPLOADS, AND FINALLY STACK UPLOADS.
      - python3.6 automation-stack-sync.py
