
---
version: 0.2

phases:
  install:
    commands:
      - pip install awscli --upgrade --user
      - pip install gitpython

  build:
    commands:
      # STEP1: FILTER FILES TO ONLY ONES MODIFIED FROM GIT - COPY THESE FILES TO A NEW DIR (templates-changed) UNDER THE SAME FOLDER STRUCTURE
      - python automation-changed-files-filter.py

      # STEP2: EXECUTE CF_NAG ON THAT NEW DIR - CF NAG WILL GO THROUGH THE DIRECTORY RECURSIVELY.

      # STEP3: ANY ADDITIONAL RULES YOU WISH TO EXECUTE (as list of lambda arns - executed sync)
      - python automation-lambda-tests.py
